# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 7.0'
gem 'better_docs', path: File.expand_path('..', __dir__)

gem 'puma', '~> 6.0'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'  # Required by ActiveRecord even though we don't use it

